---
driver:
  name: dokken
  chef_version: 14.13.11
  privileged: true
  userns_host: true

transport:
  name: dokken

provisioner:
  name: dokken
  always_update_cookbooks: true
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      image: dokken/centos-7
      pid_one_command: /usr/lib/systemd/systemd

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    verifier:
      inspec_tests:
        - test/smoke/default
