name 'apache'
maintainer 'Company'
maintainer_email 'company@company.org'
license 'All Rights Reserved'
description 'Installs/Configures apache'
long_description 'Installs/Configures apache'
version '2.0.1'
chef_version '>= 12.1' if respond_to?(:chef_version)
supports 'centos'
supports 'ubuntu'
